New Forestry Support Implementation
refinedmods/refinedstorage pull request #1370
Opened 2017-07-18 04:13 UTC by TeknoKit

At the start of any isEqual comparison, if Forestry is loaded, it determines if either item is a Forestry Bee with a GEN tag and if so flags the comparison with COMPARE_STRIP_NBT. A forestry case with the GEN tag has been added to the stripTags method.
Is this better?

2017-07-18 09:28 UTC, raoulvdberge commented
No, it's not. The comparer needs to guarantee correct compares, we can't just strip nbt when not asked to strip.

2017-07-18 09:36 UTC, way2muchnoise requested changes

2017-07-18 09:36 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/integration/forestry/IntegrationForestry.java
> +	public static int isItem(int flags, ItemStack... items) {
This method is kind ambiguous as `isItem` should return a `boolean` indicating whether it is a forestry item or not. Would rather see this method replace with something like a `isBee` method that takes a single `ItemStack`.

2017-07-18 09:36 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/apiimpl/util/Comparer.java
> +        	flags = IntegrationForestry.isItem(flags, items);
Changing the flag here seems kinda off. I would propose adding a method in `IntegrationForestry` along the lines of `sanitise`, where it removes then tags that need to be removed without changing the comparison flags. The this if would be looking more like this:

```java
if (IntegrationForestry.isLoaded()) {
    if (IntegrationForestry.isBee(left) {
        left = IntegrationForestry.sanitise(left.copy());
    }
    if (IntegrationForestry.isBee(right)) {
        right = IntegrationForestry.sanitise(right.copy());
    }
}
```

In this approach `sanitise` could be added to or changed without changing this code.

2017-07-18 09:36 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/apiimpl/util/Comparer.java
> +        	flags = IntegrationForestry.isItem(flags, items);
This `isBee` method could be changed to something that would also support trees and butterflies. And name it appropriately, eg. `isBreedable`.

2017-07-18 09:36 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/integration/forestry/IntegrationForestry.java
> +	public static int isItem(int flags, ItemStack... items) {
As mentioned in the other comment it would be nice if this also had support for trees and butterflies. Might as well go all with this support.

2017-07-18 10:08 UTC, TeknoKit commented
I was under the impression that modifying NBT tags directly outside of comparison was not wanted and thus tried to integrate it to the one method that did such operations but wanted to avoid that for your stated reason the first time. Either way I do understand why it was better to be moved.
I am also sure that moving above the IComparer is a bad idea; trying to ensure all the different items that can extract and insert all accommodate for these items is bound to just get messy and mistakes made.

Yes, I could fairly quickly add in trees and butterflies once I understand the NBTCompounds.
I'll get this right eventually, but I did need some gauging to see the proper mindset here. I'll work on it.

2017-07-18 23:29 UTC, TeknoKit commented
I think setting appropriate methods with a sanitize flag is better than altering the default behavior and then trying to blacklist some methods. I'll change that behavior back and put the flags in properly.

2017-07-19 09:16 UTC, way2muchnoise commented
This is starting to look at lot better than before, keep up the good work!

2017-07-22 04:58 UTC, TeknoKit commented
Should I just re-base the fork at this point?

2017-07-22 05:08 UTC, TeknoKit commented
I'll re-fork and start a new pull once this is fixed.

2017-07-22 05:08 UTC, closed without merging