Allow crafters to be daisy-chained
refinedmods/refinedstorage pull request #1740
Opened 2018-04-08 02:17 UTC by tomKPZ

In crafting situations that require more than the 9 blocking patterns
that one crafter allows, the only solution is to duplicate the setup
to allow a second crafter.  This CL allows crafters to be
daisy-chained to provide a solution to this issue.

Also, since unlimited crafters can now be placed on a single
inventory, this eliminates the need to have multiple intermediate
inventories which then pipe into the desired inventory.  This also
improves the crafting manager UI as now those patterns can all be
listed under one "Furnace" instead of (potentially multiple) "Chest"s.

2018-04-08 10:00 UTC, way2muchnoise commented
Could you add a picture or maybe a small video of how this exactly looks in world?

2018-04-08 18:31 UTC, tomKPZ commented
Here's a demo:
https://www.youtube.com/watch?v=cH5ITjsbCc8

You might have noticed a bug at the end of the video where the crafter manager showed the two crafters I added under "Crafter" rather than "Chest".  I was briefly confused :)  However, this was easily fixed in the latest revision by rebuilding the crafting manager when a crafter is rotated.

2018-04-09 10:09 UTC, raoulvdberge commented
You're still making lots of changes, so if you believe this is bug free and ready for review, let me know.

2018-04-09 14:59 UTC, tanderson-google commented
Should be ready at this point

2018-04-09 15:00 UTC, tomKPZ commented
Should be ready at this point

2018-04-09 22:25 UTC, Saklad5 commented
This is a spectacularly good idea. There’s a lot of automation ideas I’ve decided against purely because I’d have to replicate the build to add more than nine recipes.

2018-04-09 22:30 UTC, Saklad5 commented
And I hate adding unnecessary steps like a buffer chest. Even something as simple as a chest can make failures more likely.

It’d be great if Crafters could output directly to pipes as well, but that might be a little finicky to implement.

2018-04-15 14:48 UTC, tomKPZ commented
friendly ping :)

2018-04-15 15:00 UTC, raoulvdberge commented
I am going to release a new version soon, and this PR will be merged *after* that.

2018-04-23 15:54 UTC, raoulvdberge requested changes

2018-04-23 15:54 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/apiimpl/autocrafting/CraftingManager.java
> +    public void addContainerBlock(UUID blocker, UUID blockee) {
Why is it necessary to store `blocker`?

2018-04-23 15:54 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/apiimpl/network/node/NetworkNodeCrafter.java
> +    public void setBlocked(INetwork network, boolean blocked) {
With the extra `network` parameter, and this method having no side-effects for `NetworkNodeCrafter` anymore, I feel like this method can be removed and moved to `CraftingManager`.

2018-04-23 15:54 UTC, raoulvdberge commented on CHANGELOG.md
> +- Allow crafters to be daisy-chained (tomKPZ)
Can you move this entry to a new 1.5.34 list in the changelog?

2018-04-23 15:54 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/api/autocrafting/ICraftingPatternContainer.java
> +     * another one, gets the last container in the chain.  If containers are
last container? Don't you mean first container? The root one (the one at front) is the first one.

2018-04-23 15:54 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/api/autocrafting/ICraftingPatternContainer.java
> +    ICraftingPatternContainer getProxyPatternContainer();
I'd call this one `getRootContainer`.

2018-04-24 02:42 UTC, tomKPZ commented
Did all of the things.

2018-04-24 05:34 UTC, raoulvdberge commented
Thank you, great PR!

2018-04-24 05:34 UTC, raoulvdberge approved these changes

2018-04-24 05:34 UTC, merged