RS API Extension - Network Energy Core
refinedmods/refinedstorage pull request #1829
Opened 2018-06-22 09:48 UTC by Samtrion

+ added also Config option to adjust max receive rate for the controller

2018-06-23 09:00 UTC, raoulvdberge requested changes
Thank you for your PR, but there is still some work to be done.

2018-06-24 16:53 UTC, Samtrion commented
Thanks for the review, i will fix this 😀

2018-06-25 07:37 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/RSConfig.java
> +        controllerMaxReceive = config.getInt("controllerMaxReceive", ENERGY, Integer.MAX_VALUE, 0, Integer.MAX_VALUE, "The maximum RF the controller receives per Tick");
Change RF into "energy" and lowercase "Tick"

2018-06-25 14:10 UTC, Samtrion commented on src/main/java/com/raoulvdberge/refinedstorage/api/network/INetwork.java
> +    int getNetworkEnergyUsage();
To differentiate between `INetwork.getEnergyUsage()` and `INetworkNode.getEnergyUsage()` to exclude possible side effects.

2018-06-25 14:14 UTC, Samtrion commented on src/main/java/com/raoulvdberge/refinedstorage/api/energy/IEnergyCore.java
> +public interface IEnergyCore {
Surely the name `IEnergy` is enough.
As part of this, I would also rename 'EnergyForgeCoreProxy' to 'EnergyProxy' and 'EnergyForgeCore' to 'Energy'

2018-06-25 14:16 UTC, Samtrion commented on src/main/java/com/raoulvdberge/refinedstorage/api/energy/IEnergyCore.java
> +import net.minecraftforge.energy.IEnergyStorage;
That's a leftover of a test. :(

2018-06-25 14:35 UTC, Samtrion commented on src/main/java/com/raoulvdberge/refinedstorage/api/network/INetwork.java
> +    int getNetworkEnergyUsage();
But that is obsolete as the nodes control the energy consum.

2018-06-25 15:24 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/api/energy/EnergyProxy.java
> +	public EnergyProxy(IEnergy energyCore, int maxTransfer) {
Rename to energy

2018-06-25 15:24 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/api/energy/EnergyProxy.java
> +		this.energy = energyCore;
Rename energyCore to energy

2018-06-25 15:24 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/api/energy/IEnergy.java
> +	int getMaxEnergy();
getCapacity

2018-06-25 15:24 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/api/energy/IEnergy.java
> +	int receive(int amount, boolean simulate);
insert (to be analog with "extract")

2018-06-25 15:25 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/api/energy/IEnergy.java
> +	void setStored(int energyAmount);
energy instead of energyAmount

2018-06-25 16:14 UTC, Samtrion commented
Sorry, I'm still fighting a bit with the JAVA IDE of my choice.
Hope I have now treated all Stylebreaks.

2018-06-25 16:57 UTC, merged