Curio support
refinedmods/refinedstorage pull request #3013
Opened 2021-06-13 10:04 UTC by Darkere

see #3012

2021-06-14 19:30 UTC, starforcraft commented
lol https://www.curseforge.com/minecraft/mc-mods/refined-curios this mod is useless now

2021-06-14 19:40 UTC, raoulvdberge commented
I don't believe such functionality needs to be an addon

2021-06-14 19:47 UTC, starforcraft commented
> I don't believe such functionality needs to be an addon

yeah true was actually a bit stupid to do a addon mod instead of just a PR

2021-06-14 20:23 UTC, Darkere commented
Lol. Did not even think to look if there is an addon. Timing is too good too :D

looks like the plan is to not merge this for 1.9.13 so you might still have some time before this happens.

2021-06-16 07:38 UTC, raoulvdberge requested changes

2021-06-16 07:38 UTC, raoulvdberge commented on src/main/java/com/refinedmods/refinedstorage/network/OpenNetworkItemMessage.java
> +        return new OpenNetworkItemMessage(buf.readInt(), buf.readString(32767));
I think we have a util function for this?

2021-06-16 07:38 UTC, raoulvdberge commented on src/main/java/com/refinedmods/refinedstorage/network/OpenNetworkItemMessage.java
> +                    LazyOptional<ICuriosItemHandler> curiosHandler = CuriosApi.getCuriosHelper().getCuriosHandler(player);
Please split this code a bit more up, it's too much lines / too much indentation in a single method.

2021-06-16 07:38 UTC, raoulvdberge commented on src/main/java/com/refinedmods/refinedstorage/screen/KeyInputListener.java
> +            AtomicReference<Boolean> found = new AtomicReference<>();
I think we can do better than this.

2021-06-16 07:38 UTC, raoulvdberge commented on src/main/java/com/refinedmods/refinedstorage/screen/KeyInputListener.java
> +        if (CuriosIntegration.isLoaded() && slotFound == -1) {
Please split this method a bit more up.

2021-06-17 08:52 UTC, raoulvdberge reviewed
LGTM. Did you try launching the game without Curios installed to see if it won't break?

2021-06-17 21:42 UTC, Darkere commented
Working just fine.

2021-06-18 05:41 UTC, raoulvdberge commented
Thx

2021-06-18 05:41 UTC, merged