Enabling Player based crafting recipes autocrafting
refinedmods/refinedstorage pull request #3041
Opened 2021-07-17 20:43 UTC by mcenderdragon

This is wurrently a WIP PR as right now I cant test it becuase gradle suddenly broke after my setup worked fully, and gradle was not even running.

This adds a player to the Pattern Container & stored the creator of a pattern in the NBT of the item.
And it adds more info to the DummyCraftingInventory so recipes which are player based (for example futurepack) can use this player/UUD and research recipes are fianlly available for auocrafting.

I tried to add the player who requested a crafting to everythign but noticed: I only check thath in the match function so when the Pattern is laoded from the item, match is then never checked again so it would help my problem here.

2021-07-18 12:06 UTC, Darkere requested changes
Had a quick look. Haven't tried anything yet though.

2021-07-18 12:11 UTC, mcenderdragon commented on src/main/java/com/refinedmods/refinedstorage/api/network/INetwork.java
> +
fixed

2021-07-18 12:11 UTC, mcenderdragon commented on build.gradle
> +
fixed

2021-07-18 12:11 UTC, mcenderdragon commented on src/main/java/com/refinedmods/refinedstorage/apiimpl/network/node/GridNetworkNode.java
> +
fixed

2021-07-18 12:15 UTC, mcenderdragon commented
to test add 
```
 maven {
        url "https://www.moadmaven.dev.com"
        content {
            includeGroup "curse.maven"
        }
    }
```
And 

```
	runtimeOnly fg.deobf("redsnakegames.mcenderdragon:futurepack:1.16.4-31.2.6878")
	compileOnly fg.deobf("redsnakegames.mcenderdragon:futurepack:1.16.4-31.2.6878:api") 
```

To the build script. ANd then its posssible to craft patterns with futurepack recipes & also craft them. use `/futurepack research Dev unlock all` to get all researches so the recipes are available to you.

2021-09-20 17:07 UTC, Darkere commented
So uh... I took a closer look at the code. This is... a hack to get support for your own mod in. 

At no point does your code interact with the underlying forge/minecraft code to make things compatible with other mods using the crafting system. Compatibility with other mods is something we want, but not by having random unused fields in classes. 

Sorry I don't think this is going to have a chance like it is.

2021-09-20 17:13 UTC, mcenderdragon commented
> 
> 
> So uh... I took a closer look at the code. This is... a hack to get support for your own mod in.
> 
> At no point does your code interact with the underlying forge/minecraft code to make things compatible with other mods using the crafting system. Compatibility with other mods is something we want, but not by having random unused fields in classes.
> 
> Sorry I don't think this is going to have a chance like it is.

That is true. I am open to other implementations, the problem is Forge has a "current crafting player" in ForgeHooks, but the time this is used is to late since there is no player when the patterns are loaded and the "matches" function is called in IRecipe. I added those fields to pass more information to the IRecipe since that only gets the CraftingInventory

2021-09-20 20:56 UTC, mcenderdragon commented
Current issue with latest changes: it doenst work client side, because of the pattern cahce and the fake player is only set on server side.

2022-05-27 13:58 UTC, raoulvdberge requested changes
Can this be re-targeted for 1.18 (`develop`)

2022-07-24 07:01 UTC, raoulvdberge commented
This is still targeting 1.16. Feel free to open a new PR for `develop`

2022-07-24 07:01 UTC, closed without merging