Regulator Functionality for Exporter
refinedmods/refinedstorage pull request #744
Opened 2016-12-11 23:00 UTC by InusualZ

It does not handle the GUI correctly

2016-12-11 23:07 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/tile/TileExporter.java
> +                                            return;
This seems like a very odd place to return. Shouldn't it be some kind of break

2016-12-11 23:07 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/tile/TileExporter.java
> +                                    if (slot.isItemEqual(handler.getStackInSlot(index))) {
You call `handler.getStackInSlot(index)` you might want to put that in a var

2016-12-11 23:07 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/tile/TileExporter.java
> +                                            stackSize = upgrades.hasUpgrade(ItemUpgrade.TYPE_STACK) ? slot.getCount() - handler.getStackInSlot(index).getCount() : 1;
Shouldn't this also break after this?

2016-12-11 23:07 UTC, raoulvdberge requested changes

2016-12-11 23:07 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/gui/sidebutton/SideButtonRegulator.java
> +
Unneeded new line

2016-12-11 23:07 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/tile/TileExporter.java
> +                                for(int index = 0; i< handler.getSlots(); i++) {
Coding style
- for (
- i < handler.getSlots()

2016-12-11 23:07 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/tile/TileExporter.java
> +                                    if (slot.isItemEqual(handler.getStackInSlot(index))) {
Use API.instance().getComparer().isEqualNoQuantity()

2016-12-11 23:07 UTC, raoulvdberge commented on src/main/resources/assets/refinedstorage/lang/en_US.lang
> +sidebutton.refinedstorage:exporter.regulator=Regulate the export rate
Call this "Regulator Mode"

2016-12-11 23:10 UTC, raoulvdberge commented
This doesn't seem to handle fluids yet, too.

2016-12-11 23:47 UTC, InusualZ commented on src/main/java/com/raoulvdberge/refinedstorage/tile/TileExporter.java
> +                                            stackSize = upgrades.hasUpgrade(ItemUpgrade.TYPE_STACK) ? slot.getCount() - handler.getStackInSlot(index).getCount() : 1;
What if there is multiple stack of the same item/block

2016-12-11 23:47 UTC, InusualZ commented on src/main/java/com/raoulvdberge/refinedstorage/tile/TileExporter.java
> +                                            return;
If I don't return here would insert the item/block anyway

2016-12-12 06:53 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/tile/TileExporter.java
> +                                    if (API.instance().getComparer().isEqualNoQuantity(slot, handlerStack)) {
Actually, you might wanna use isEqual(slot, handlerStack, compare) here instead.

2016-12-12 21:55 UTC, way2muchnoise approved these changes

2016-12-12 22:01 UTC, raoulvdberge approved these changes

2016-12-12 22:01 UTC, merged