Blocking Mode for pattern
refinedmods/refinedstorage pull request #785
Opened 2016-12-26 00:58 UTC by InusualZ

Urgent review!
* Variable Names
* Localization Names
* Method Description
* Checkbox position (Grid checkbox is awfully placed!)

2016-12-26 00:59 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/apiimpl/autocrafting/CraftingPattern.java
> +    private boolean blockingTask = false;
what's the use of this variable?

2016-12-26 01:00 UTC, raoulvdberge commented on src/main/resources/assets/refinedstorage/lang/en_US.lang
> +misc.refinedstorage:blocking_task=Blocking Mode
we should just have one language key, that just says "Blocking"

2016-12-26 14:12 UTC, InusualZ commented
Updated with a new approach. I'm have encountered a bug, but I don't know how to fix or what I have done wrong. When I restart the client the system doesn't recognize the pattern.

Picture of the result:
![pattern-encoder](http://imgur.com/kzNuS1Q)
![crafting-monitor](http://imgur.com/fBRyLeG)
![pattern-grid](http://imgur.com/OLPLjbR)

PD: I don't think the pattern grid blocking feature is needed.

2016-12-26 14:23 UTC, raoulvdberge commented
Yeah, I agree. Pattern grid doesn't need it I think. So, 2 questions:

- What do you mean with "When I restart the client, the system doesn't recognize the pattern."
- Does it work if a pattern that isn't blocked needs an item that IS blocked. Does that work correctly in the chain?

2016-12-27 09:26 UTC, way2muchnoise requested changes
Start looking pretty good :+1:

2016-12-27 09:26 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/api/autocrafting/task/ICraftingStep.java
> +    boolean isBlocked();
Do we really need this?

2016-12-27 09:26 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/apiimpl/autocrafting/task/CraftingTask.java
> +                        if (step.getPattern().isBlockingPattern()) {
Might want to move this to `step.setStartedProcessing()`

2016-12-27 09:26 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/apiimpl/autocrafting/task/CraftingTask.java
> +                            element = new CraftingMonitorElementError(element, "gui.refinedstorage:crafting_monitor.blocked");
I can see why you would need `step.isBlocked()` but is `Machine in use` not kinda the same? imo not really needed. paging @raoulvdberge for this one

2016-12-27 13:55 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/apiimpl/autocrafting/task/CraftingTask.java
> +                            element = new CraftingMonitorElementError(element, "gui.refinedstorage:crafting_monitor.blocked");
nah this is fine. they're 2 different things

2016-12-27 15:06 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/apiimpl/network/node/NetworkNodeCrafter.java
> +        blocked = value;
call markDirty here

2016-12-27 15:07 UTC, raoulvdberge commented on src/main/java/com/raoulvdberge/refinedstorage/api/autocrafting/ICraftingPattern.java
> +    boolean isBlockingPattern();
rename to isBlocking

2016-12-27 15:10 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/apiimpl/autocrafting/task/CraftingTask.java
> +                            element = new CraftingMonitorElementError(element, "gui.refinedstorage:crafting_monitor.blocked");
This should then be `step.getPattern().getContainer().isBlocked()` which eliminates the use of `ICraftingStep#isBlocked()`

2016-12-27 15:11 UTC, way2muchnoise commented on src/main/java/com/raoulvdberge/refinedstorage/apiimpl/autocrafting/task/CraftingTask.java
> +                if ((container.isBlocked() && !step.getPattern().isProcessing()) || !container.isBlocked()) {
Should be `!step.getPattern().isProcessing() || !container.isBlocked()`

2016-12-27 15:34 UTC, way2muchnoise approved these changes

2016-12-27 15:44 UTC, merged